name: Deploy site
on:
  workflow_dispatch:
  push:
    branches: ["gh-pages"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - run: pwd && ls

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          clean: false
          path: main

      - run: pwd && ls
      - run: cd main
      - run: pwd && ls
